//! Core traits and rendering context for Helix configuration.

/// Rendering context passed during Helix config generation.
///
/// Helix uses TOML, which is flat by nature — `HelixRenderContext` is kept
/// minimal for now but provides a stable hook for future options (e.g.
/// emitting comment headers).
#[derive(Debug, Clone, Default)]
pub struct HelixRenderContext {
    /// When `true`, optional doc-comment lines are emitted above each node.
    pub emit_comments: bool,
}

/// Central trait for all Helix configuration nodes.
///
/// Intentionally **distinct** from [`crate::core::Config`] (Neovim) and
/// [`crate::hyprland::HyprlandConfig`] (Hyprland) so that nodes from
/// different tools cannot be accidentally mixed in the same configuration
/// tree.
pub trait HelixConfig {
    /// Render this node into a TOML string fragment.
    fn render(&self, ctx: &HelixRenderContext) -> String;

    /// Convenience: render with a default context.
    fn generate(&self) -> String {
        self.render(&HelixRenderContext::default())
    }

    /// Optional pre-render validation hook.
    fn validate(&self) -> Result<(), String> {
        Ok(())
    }
}

/// Top-level Helix `config.toml` configuration tree.
///
/// Collects all configuration nodes and renders them as a single TOML
/// document.  Only [`HelixConfig`] nodes are accepted; mixing in Neovim or
/// Hyprland nodes is a compile-time error.
///
/// # Example
/// ```
/// use toconfig::helix::{HelixConfig, HelixConfigTree, ThemeSetting};
/// use toconfig::helix::editor::EditorSection;
///
/// let tree = HelixConfigTree::new()
///     .with_comment("config.toml — generated by toconfig")
///     .push(ThemeSetting::new("gruvbox_dark"))
///     .push(EditorSection::new().mouse(false).line_number("relative"));
///
/// let out = tree.generate();
/// assert!(out.contains("theme = \"gruvbox_dark\""));
/// assert!(out.contains("[editor]"));
/// ```
pub struct HelixConfigTree {
    pub nodes: Vec<Box<dyn HelixConfig>>,
    pub header_comment: Option<String>,
}

impl Default for HelixConfigTree {
    fn default() -> Self {
        Self::new()
    }
}

impl HelixConfigTree {
    pub fn new() -> Self {
        Self {
            nodes: Vec::new(),
            header_comment: None,
        }
    }

    /// Attach a header comment block at the top of the generated file.
    pub fn with_comment(mut self, comment: &str) -> Self {
        self.header_comment = Some(comment.to_string());
        self
    }

    /// Append a node (mutable borrow, returns `&mut Self` for chaining).
    pub fn add<C: HelixConfig + 'static>(&mut self, node: C) -> &mut Self {
        self.nodes.push(Box::new(node));
        self
    }

    /// Append a node (consuming, returns `Self` for builder chains).
    pub fn push<C: HelixConfig + 'static>(mut self, node: C) -> Self {
        self.nodes.push(Box::new(node));
        self
    }

    /// Validate all child nodes, collecting every error.
    pub fn validate_all(&self) -> Result<(), Vec<String>> {
        let errors: Vec<String> = self
            .nodes
            .iter()
            .filter_map(|n| n.validate().err())
            .collect();
        if errors.is_empty() {
            Ok(())
        } else {
            Err(errors)
        }
    }
}

impl HelixConfig for HelixConfigTree {
    fn render(&self, ctx: &HelixRenderContext) -> String {
        let mut parts: Vec<String> = Vec::new();
        if let Some(ref c) = self.header_comment {
            for line in c.lines() {
                parts.push(format!("# {}", line));
            }
        }
        for node in &self.nodes {
            let rendered = node.render(ctx);
            if !rendered.is_empty() {
                parts.push(rendered);
            }
        }
        parts.join("\n\n")
    }
}

// ── Internal TOML rendering helpers ──────────────────────────────────────────

/// Format a boolean as a TOML literal.
pub(crate) fn toml_bool(v: bool) -> &'static str {
    if v { "true" } else { "false" }
}

/// Format a string as a quoted TOML string.
pub(crate) fn toml_str(s: &str) -> String {
    format!("\"{}\"", s)
}

/// Format a slice of strings as a TOML inline array, e.g. `["a", "b"]`.
pub(crate) fn toml_str_array(items: &[String]) -> String {
    let inner: Vec<String> = items.iter().map(|s| toml_str(s)).collect();
    format!("[{}]", inner.join(", "))
}
