//! Helix editor configuration builder.
//!
//! Generates `~/.config/helix/config.toml` from type-safe Rust structs.
//! Every node implements [`HelixConfig`] and is collected in a
//! [`HelixConfigTree`].  The trait is **distinct** from
//! [`crate::core::Config`] (Neovim) and [`crate::hyprland::HyprlandConfig`]
//! (Hyprland) so that nodes from different tools cannot be accidentally mixed
//! in the same configuration tree.
//!
//! # Quick-start example
//! ```
//! use toconfig::helix::{HelixConfig, HelixConfigTree, ThemeSetting};
//! use toconfig::helix::editor::{EditorSection, LineNumber};
//! use toconfig::helix::keys::{KeysSection, KeyMode, KeyAction};
//!
//! let tree = HelixConfigTree::new()
//!     .with_comment("config.toml — generated by toconfig")
//!     .push(ThemeSetting::new("gruvbox_dark"))
//!     .push(
//!         EditorSection::new()
//!             .line_number("relative")
//!             .mouse(false)
//!             .scrolloff(5),
//!     )
//!     .push(
//!         KeysSection::new(KeyMode::Normal)
//!             .cmd("C-s", ":write")
//!             .cmd("C-q", ":quit"),
//!     );
//!
//! println!("{}", tree.generate());
//! ```

pub mod core;
pub mod editor;
pub mod keys;
pub mod section;
pub mod theme;

// ── Core re-exports ───────────────────────────────────────────────────────────
pub use core::{HelixConfig, HelixConfigTree, HelixRenderContext};

// ── Sub-module re-exports ─────────────────────────────────────────────────────
pub use editor::{
    Bufferline, CursorKind, CursorShapeSection, EditorSection, FilePickerSection,
    IndentGuidesSection, LineNumber, LspSection, SearchSection, SoftWrapSection, StatuslineElement,
    StatuslineSection,
};
pub use keys::{KeyAction, KeyBinding, KeyMode, KeysSection};
pub use section::{RawToml, TomlEntry, TomlSection};
pub use theme::ThemeSetting;
