//! Systemd unit-file configuration builder.
//!
//! Generates `.service`, `.socket`, `.timer`, `.mount`, `.automount`, `.path`,
//! `.swap` unit files and drop-in overrides from type-safe Rust structs.
//! Every section struct implements [`SystemdConfig`] and is collected in a
//! [`SystemdUnit`] (or a [`DropIn`] for overrides).
//!
//! # Unit types supported
//!
//! | Rust type           | Systemd unit kind  | Key section        |
//! |---------------------|--------------------|--------------------|
//! | [`SystemdUnit`]     | any                | (container)        |
//! | [`ServiceSection`]  | `.service`         | `[Service]`        |
//! | [`SocketSection`]   | `.socket`          | `[Socket]`         |
//! | [`TimerSection`]    | `.timer`           | `[Timer]`          |
//! | [`MountSection`]    | `.mount`           | `[Mount]`          |
//! | [`AutomountSection`]| `.automount`       | `[Automount]`      |
//! | [`PathSection`]     | `.path`            | `[Path]`           |
//! | [`SwapSection`]     | `.swap`            | `[Swap]`           |
//! | [`DropIn`]          | any (override)     | any section        |
//!
//! # Quick-start example
//! ```
//! use toconfig::systemd::{SystemdConfig, SystemdUnit};
//! use toconfig::systemd::unit_section::UnitSection;
//! use toconfig::systemd::service::{ServiceSection, ServiceType, Restart};
//! use toconfig::systemd::install::InstallSection;
//!
//! let unit = SystemdUnit::new()
//!     .with_comment("my-daemon.service — generated by toconfig")
//!     .push(
//!         UnitSection::new()
//!             .description("My background daemon")
//!             .after("network-online.target"),
//!     )
//!     .push(
//!         ServiceSection::new()
//!             .service_type(ServiceType::Simple)
//!             .exec_start("/usr/bin/my-daemon --config /etc/my-daemon.conf")
//!             .restart(Restart::OnFailure)
//!             .restart_sec("5s"),
//!     )
//!     .push(InstallSection::new().wanted_by("multi-user.target"));
//!
//! println!("{}", unit.generate());
//! ```

pub mod automount;
pub mod core;
pub mod drop_in;
pub mod install;
pub mod mount;
pub mod path;
pub mod section;
pub mod service;
pub mod socket;
pub mod swap;
pub mod timer;
pub mod unit_section;

// ── Core re-exports ───────────────────────────────────────────────────────────
pub use core::{SystemdConfig, SystemdRenderContext, SystemdUnit};

// ── Sub-module re-exports ─────────────────────────────────────────────────────
pub use automount::AutomountSection;
pub use drop_in::DropIn;
pub use install::InstallSection;
pub use mount::MountSection;
pub use path::PathSection;
pub use section::{RawSystemd, SectionEntry, SystemdSection};
pub use service::{Restart, ServiceSection, ServiceType};
pub use socket::SocketSection;
pub use swap::SwapSection;
pub use timer::TimerSection;
pub use unit_section::UnitSection;
