//! Hyprland window manager configuration builder.
//!
//! Generates `~/.config/hypr/hyprland.conf` from type-safe Rust structs.
//!
//! This module is intentionally **separate** from the Neovim [`crate::core::Config`]
//! trait family. Hyprland nodes implement [`HyprlandConfig`] and are collected in a
//! [`HyprlandConfigTree`]. Neovim [`crate::core::Config`] nodes implement the nvim
//! `Config` trait and live in a Neovim [`crate::core::ConfigTree`]. The two traits are
//! distinct, so the Rust compiler prevents mixing them in the same tree at compile time.
//!
//! # Quick-start example
//! ```
//! use toconfig::hyprland::{
//!     HyprlandConfig, HyprlandConfigTree, Variable, EnvVar, MonitorConfig,
//!     Bind, Dispatcher, WindowRule, AnimationsSection, Bezier, Animation,
//!     DwindleLayout, XWaylandSection,
//! };
//! use toconfig::hyprland::exec::ExecOnce;
//! use toconfig::hyprland::section::Section;
//!
//! let mut tree = HyprlandConfigTree::new()
//!     .with_comment("hyprland.conf — generated by toconfig");
//!
//! tree.add(Variable::new("terminal", "kitty"))
//!     .add(Variable::new("browser", "firefox"))
//!     .add(MonitorConfig::new("eDP-1", "1920x1080@60", "0x0", 1.0))
//!     .add(EnvVar::xcursor_size(24))
//!     .add(ExecOnce::new("waybar"))
//!     .add(
//!         Section::new("general")
//!             .pair("gaps_in", "5")
//!             .pair("gaps_out", "20")
//!             .pair("border_size", "2"),
//!     )
//!     .add(Bind::new("SUPER", "Return", Dispatcher::Exec("$terminal".into())))
//!     .add(Bind::new("SUPER", "Q", Dispatcher::KillActive))
//!     .add(WindowRule::new("float", "class:^(pavucontrol)$"))
//!     .add(
//!         AnimationsSection::new()
//!             .bezier(Bezier::ease_out_back("myBezier"))
//!             .animation(Animation::new("windows", 7.0, "myBezier").style("slide")),
//!     )
//!     .add(DwindleLayout::new().pseudotile(true).preserve_split(true))
//!     .add(XWaylandSection::new().force_zero_scaling(true));
//!
//! println!("{}", tree.generate());
//! ```

pub mod animation;
pub mod bind;
pub mod core;
pub mod environment;
pub mod exec;
pub mod layout;
pub mod monitor;
pub mod output;
pub mod permission;
pub mod section;
pub mod variable;
pub mod window_rule;
pub mod workspace;
pub mod xwayland;

// ── Core re-exports ───────────────────────────────────────────────────────────
pub use core::{HyprlandConfig, HyprlandConfigTree, HyprlandRenderContext};

// ── Sub-module re-exports ─────────────────────────────────────────────────────
pub use animation::{Animation, AnimationsSection, Bezier};
pub use bind::{Bind, BindFlags, Dispatcher};
pub use environment::EnvVar;
pub use exec::{Exec, ExecOnce, PluginLoad, Source};
pub use layout::{DwindleLayout, MasterLayout, MonocleLayout, ScrollingLayout};
pub use monitor::MonitorConfig;
pub use output::HyprlandOutput;
pub use permission::{Permission, PermissionAction, PermissionType};
pub use section::{RawHyprland, Section};
pub use variable::Variable;
pub use window_rule::WindowRule;
pub use workspace::WorkspaceRule;
pub use xwayland::XWaylandSection;
