//! Ghostty terminal emulator configuration builder.
//!
//! # Module Overview
//!
//! | Sub-module          | Purpose                                                  |
//! |---------------------|----------------------------------------------------------|
//! | [`core`]            | `GhosttyConfig` trait, `GhosttyRenderContext`, `GhosttyConfigTree` |
//! | [`color`]           | `HexColor`, `ThemeSpec`, `ColorConfig`                   |
//! | [`font`]            | `FontConfig`, `FontSyntheticStyle`                       |
//! | [`window`]          | `WindowConfig`, `WindowDecoration`, `WindowSaveState`    |
//! | [`cursor`]          | `CursorConfig`, `CursorStyle`                            |
//! | [`terminal`]        | `TerminalConfig`, `ClipboardAccess`                      |
//! | [`shell`]           | `ShellConfig`, `ShellIntegration`                        |
//! | [`mouse`]           | `MouseConfig`                                            |
//! | [`keybind`]         | `Keybind`, `KeybindAction`, `KeybindGroup`               |
//! | [`platform`]        | `GtkConfig`, `MacosConfig`                               |
//! | [`misc`]            | `MiscConfig` (quit, bell, auto-update, …)                |
//! | [`section`]         | `GhosttyComment`, `GhosttyBlankLine`, `RawGhostty`       |
//! | [`output`]          | `GhosttyOutput` — file writer with diff-check            |
//!
//! # Quick-start example
//!
//! ```rust
//! use toconfig::ghostty::{
//!     GhosttyConfigTree,
//!     color::{ColorConfig, HexColor, ThemeSpec},
//!     font::FontConfig,
//!     keybind::{KeybindAction, KeybindGroup},
//!     section::GhosttyBlankLine,
//! };
//!
//! let bg = HexColor::new("#1e1e2e").unwrap();
//! let fg = HexColor::new("#cdd6f4").unwrap();
//!
//! let mut tree = GhosttyConfigTree::new()
//!     .with_header("Generated by toconfig");
//!
//! tree.push(FontConfig::new().family("JetBrains Mono").size(13.0))
//!     .push(ColorConfig::new()
//!         .theme(ThemeSpec::single("Catppuccin Mocha"))
//!         .background(bg)
//!         .foreground(fg))
//!     .push(GhosttyBlankLine)
//!     .push(KeybindGroup::new()
//!         .bind("ctrl+shift+c", KeybindAction::CopyToClipboard)
//!         .bind("ctrl+shift+v", KeybindAction::PasteFromClipboard));
//!
//! println!("{}", tree.generate());
//! ```

pub mod color;
pub mod core;
pub mod cursor;
pub mod font;
pub mod keybind;
pub mod misc;
pub mod mouse;
pub mod output;
pub mod platform;
pub mod section;
pub mod shell;
pub mod terminal;
pub mod window;

// ── Top-level convenience re-exports ─────────────────────────────────────────

pub use color::{ColorConfig, HexColor, ThemeSpec};
pub use core::{GhosttyConfig, GhosttyConfigTree, GhosttyRenderContext};
pub use cursor::{CursorConfig, CursorStyle};
pub use font::{FontConfig, FontSyntheticStyle};
pub use keybind::{Keybind, KeybindAction, KeybindGroup};
pub use misc::{AutoUpdateChannel, BellFeature, MiscConfig};
pub use mouse::MouseConfig;
pub use output::GhosttyOutput;
pub use platform::{
    GtkConfig, GtkTabsLocation, MacosConfig, MacosOptionAsAlt, MacosTitlebarStyle,
};
pub use section::{GhosttyBlankLine, GhosttyComment, RawGhostty};
pub use shell::{ShellConfig, ShellIntegration};
pub use terminal::{ClipboardAccess, TerminalConfig};
pub use window::{Colorspace, PaddingColor, WindowConfig, WindowDecoration, WindowSaveState};
