//! Core traits and rendering context for kitty terminal configuration.

/// Rendering context for kitty configuration (tracks indentation, though kitty.conf
/// itself is flat — indentation is used only for pretty-printing nested raw blocks).
#[derive(Debug, Clone)]
pub struct KittyRenderContext {
    pub indent_level: usize,
    pub indent_width: usize,
}

impl Default for KittyRenderContext {
    fn default() -> Self {
        Self {
            indent_level: 0,
            indent_width: 4,
        }
    }
}

impl KittyRenderContext {
    pub fn indent(&self) -> String {
        " ".repeat(self.indent_level * self.indent_width)
    }

    pub fn deeper(&self) -> Self {
        Self {
            indent_level: self.indent_level + 1,
            ..self.clone()
        }
    }
}

/// Central trait for all kitty configuration nodes.
///
/// Intentionally **distinct** from [`crate::core::Config`] (the Neovim/Lua trait)
/// and [`crate::hyprland::HyprlandConfig`] so that kitty nodes cannot be mixed
/// into the wrong configuration tree at compile time.
pub trait KittyConfig {
    /// Render this node into a kitty.conf string fragment.
    fn render(&self, ctx: &KittyRenderContext) -> String;

    /// Convenience: render with the default context.
    fn generate(&self) -> String {
        self.render(&KittyRenderContext::default())
    }

    /// Optional pre-render validation hook.
    fn validate(&self) -> Result<(), String> {
        Ok(())
    }
}

/// Top-level kitty configuration tree.
///
/// Accepts only nodes that implement [`KittyConfig`].  Nodes for other backends
/// are rejected at compile time because they implement different traits.
///
/// # Example
/// ```
/// use toconfig::kitty::{KittyConfig, KittyConfigTree};
/// use toconfig::kitty::font::FontConfig;
/// use toconfig::kitty::colors::ColorScheme;
///
/// let mut tree = KittyConfigTree::new()
///     .with_comment("kitty.conf — generated by toconfig");
/// tree.add(FontConfig::new().family("Hack Nerd Font Mono").size(13.0));
/// println!("{}", tree.generate());
/// ```
pub struct KittyConfigTree {
    pub nodes: Vec<Box<dyn KittyConfig>>,
    pub header_comment: Option<String>,
}

impl Default for KittyConfigTree {
    fn default() -> Self {
        Self::new()
    }
}

impl KittyConfigTree {
    pub fn new() -> Self {
        Self {
            nodes: Vec::new(),
            header_comment: None,
        }
    }

    /// Attach a header comment rendered at the top of the file.
    pub fn with_comment(mut self, comment: &str) -> Self {
        self.header_comment = Some(comment.to_string());
        self
    }

    /// Append a node (mutable borrow, returns `&mut Self` for chaining).
    pub fn add<C: KittyConfig + 'static>(&mut self, node: C) -> &mut Self {
        self.nodes.push(Box::new(node));
        self
    }

    /// Append a node (consuming, returns `Self` for builder chains).
    pub fn push<C: KittyConfig + 'static>(mut self, node: C) -> Self {
        self.nodes.push(Box::new(node));
        self
    }

    /// Run [`KittyConfig::validate`] on every child node.
    pub fn validate_all(&self) -> Result<(), Vec<String>> {
        let errors: Vec<String> = self
            .nodes
            .iter()
            .filter_map(|n| n.validate().err())
            .collect();
        if errors.is_empty() {
            Ok(())
        } else {
            Err(errors)
        }
    }
}

impl KittyConfig for KittyConfigTree {
    fn render(&self, ctx: &KittyRenderContext) -> String {
        let mut parts: Vec<String> = Vec::new();
        if let Some(ref c) = self.header_comment {
            for line in c.lines() {
                parts.push(format!("{}# {}", ctx.indent(), line));
            }
        }
        for node in &self.nodes {
            let rendered = node.render(ctx);
            if !rendered.is_empty() {
                parts.push(rendered);
            }
        }
        parts.join("\n")
    }
}
