//! Kitty terminal emulator configuration builder.
//!
//! Generates `~/.config/kitty/kitty.conf` from type-safe Rust structs.
//!
//! This module is intentionally **separate** from the Neovim [`crate::core::Config`]
//! and [`crate::hyprland::HyprlandConfig`] families. Kitty nodes implement
//! [`KittyConfig`] and are collected in a [`KittyConfigTree`]. The trait is
//! distinct so the Rust compiler prevents mixing kitty nodes with other trees.
//!
//! # Quick-start example
//! ```
//! use toconfig::kitty::{KittyConfig, KittyConfigTree};
//! use toconfig::kitty::font::FontConfig;
//! use toconfig::kitty::colors::ColorScheme;
//! use toconfig::kitty::window::WindowConfig;
//! use toconfig::kitty::cursor::{CursorConfig, CursorShape};
//! use toconfig::kitty::scrollback::ScrollbackConfig;
//! use toconfig::kitty::tab_bar::{TabBarConfig, TabBarStyle, TabBarEdge};
//! use toconfig::kitty::keybind::KittyKeybind;
//! use toconfig::kitty::performance::PerformanceConfig;
//! use toconfig::kitty::general::{GeneralConfig, UrlStyle};
//! use toconfig::kitty::raw::{KittyComment, KittyBlank};
//!
//! let mut tree = KittyConfigTree::new()
//!     .with_comment("kitty.conf — generated by toconfig");
//!
//! tree.add(KittyComment::new("Fonts"))
//!     .add(
//!         FontConfig::new()
//!             .family("Hack Nerd Font Mono")
//!             .size(13.0)
//!             .bold("auto")
//!             .italic("auto")
//!             .bold_italic("auto"),
//!     )
//!     .add(KittyBlank)
//!     .add(KittyComment::new("Colors"))
//!     .add(
//!         ColorScheme::new()
//!             .foreground("#cdd6f4")
//!             .background("#1e1e2e")
//!             .color0("#45475a")
//!             .color1("#f38ba8"),
//!     )
//!     .add(KittyBlank)
//!     .add(KittyComment::new("Window"))
//!     .add(
//!         WindowConfig::new()
//!             .padding_width(8)
//!             .background_opacity(0.95)
//!             .hide_window_decorations("no"),
//!     )
//!     .add(KittyBlank)
//!     .add(KittyComment::new("Cursor"))
//!     .add(
//!         CursorConfig::new()
//!             .shape(CursorShape::Beam)
//!             .blink_interval(0.5),
//!     )
//!     .add(KittyBlank)
//!     .add(KittyComment::new("Tab bar"))
//!     .add(
//!         TabBarConfig::new()
//!             .style(TabBarStyle::Powerline)
//!             .edge(TabBarEdge::Bottom),
//!     )
//!     .add(KittyBlank)
//!     .add(KittyComment::new("Keyboard shortcuts"))
//!     .add(KittyKeybind::copy())
//!     .add(KittyKeybind::paste())
//!     .add(KittyBlank)
//!     .add(KittyComment::new("Performance"))
//!     .add(
//!         PerformanceConfig::new()
//!             .repaint_delay(10)
//!             .input_delay(3)
//!             .sync_to_monitor(true),
//!     )
//!     .add(KittyBlank)
//!     .add(
//!         GeneralConfig::new()
//!             .shell("/bin/fish")
//!             .editor("nvim")
//!             .url_style(UrlStyle::Curly)
//!             .copy_on_select(true),
//!     );
//!
//! println!("{}", tree.generate());
//! ```

pub mod colors;
pub mod core;
pub mod cursor;
pub mod font;
pub mod general;
pub mod keybind;
pub mod performance;
pub mod raw;
pub mod scrollback;
pub mod tab_bar;
pub mod window;

// ── Core re-exports ───────────────────────────────────────────────────────────
pub use core::{KittyConfig, KittyConfigTree, KittyRenderContext};

// ── Sub-module re-exports ─────────────────────────────────────────────────────
pub use colors::ColorScheme;
pub use cursor::{CursorConfig, CursorShape};
pub use font::FontConfig;
pub use general::{GeneralConfig, UrlStyle};
pub use keybind::{KittyKeybind, KittyUnmap};
pub use performance::PerformanceConfig;
pub use raw::{KittyBlank, KittyComment, KittyInclude, RawKitty};
pub use scrollback::ScrollbackConfig;
pub use tab_bar::{TabBarConfig, TabBarEdge, TabBarStyle};
pub use window::WindowConfig;
