//! `/etc/fstab` configuration builder.
//!
//! Generates `/etc/fstab` from type-safe Rust structs.  Each filesystem
//! mount is represented as a [`FstabEntry`]; entries are collected in a
//! [`Fstab`].  Typed option builders for common, ext, btrfs, tmpfs, and NFS
//! filesystems live in the [`options`] sub-module.
//!
//! # Quick-start example
//! ```
//! use toconfig::fstab::{Fstab, FstabEntry};
//! use toconfig::fstab::options::{BtrfsOptions, CommonOptions, TmpfsOptions};
//!
//! let fstab = Fstab::new()
//!     .with_header("# /etc/fstab — generated by toconfig")
//!     // Root partition (btrfs, @root subvolume)
//!     .add(
//!         FstabEntry::new("UUID=abc-123", "/", "btrfs")
//!             .options(
//!                 BtrfsOptions::new()
//!                     .subvol("@root")
//!                     .compress("zstd:3")
//!                     .ssd()
//!                     .discard_async()
//!                     .space_cache("v2")
//!                     .build(),
//!             )
//!             .options(CommonOptions::new().noatime().build())
//!             .pass(0),
//!     )
//!     // Home subvolume
//!     .add(
//!         FstabEntry::new("UUID=abc-123", "/home", "btrfs")
//!             .options(BtrfsOptions::new().subvol("@home").compress("zstd:3").ssd().build())
//!             .options(CommonOptions::new().noatime().build())
//!             .pass(0),
//!     )
//!     // EFI partition
//!     .add(
//!         FstabEntry::new("UUID=EFI-0000", "/boot/efi", "vfat")
//!             .options_str("umask=0077")
//!             .dump(0)
//!             .pass(2),
//!     )
//!     // tmpfs for /tmp
//!     .add(
//!         FstabEntry::tmpfs("/tmp")
//!             .options(TmpfsOptions::new().size("4G").mode("1777").build())
//!             .options(CommonOptions::new().noexec().nosuid().nodev().build()),
//!     )
//!     // Swap
//!     .add(FstabEntry::swap("UUID=SWAP-999"));
//!
//! println!("{}", fstab.generate());
//! ```

pub mod core;
pub mod options;

// ── Re-exports ────────────────────────────────────────────────────────────────
pub use core::{Fstab, FstabEntry};
pub use options::{
    BtrfsOptions, CommonOptions, ExtOptions, MountOpt, NfsOptions, TmpfsOptions, render_opts,
};
