use crate::core::ConfigTree;
use crate::lua::LuaValue;
use crate::neovim::options::{OptionNode, OptionsBlock, default_editor_options};

/// Pre-built configuration profiles you can apply as a starting point.
pub enum Profile {
    /// Minimal sensible defaults — just editor options.
    Minimal,
    /// A more complete IDE-like default set.
    LazyIde,
}

impl Profile {
    /// Build a ConfigTree from the selected profile.
    pub fn build(self) -> ConfigTree {
        match self {
            Profile::Minimal => {
                let mut tree =
                    ConfigTree::new().with_comment("Minimal profile — generated by toconfig");
                tree.add(default_editor_options());
                tree
            }
            Profile::LazyIde => {
                let mut tree =
                    ConfigTree::new().with_comment("LazyIde profile — generated by toconfig");
                tree.add(default_editor_options());
                tree.add(
                    OptionsBlock::new()
                        .with_comment("IDE extras")
                        .add(OptionNode::opt("conceallevel", LuaValue::int(0)))
                        .add(OptionNode::opt("pumheight", LuaValue::int(10)))
                        .add(OptionNode::opt("showmode", LuaValue::bool(false)))
                        .add(OptionNode::opt("splitbelow", LuaValue::bool(true)))
                        .add(OptionNode::opt("splitright", LuaValue::bool(true)))
                        .add(OptionNode::opt("undofile", LuaValue::bool(true)))
                        .add(OptionNode::g("mapleader", LuaValue::str(" ")))
                        .add(OptionNode::g("maplocalleader", LuaValue::str(","))),
                );
                tree
            }
        }
    }
}
